############# English navigation ##############

# # main menu
# [[main]]
# name = "Home"
# url = "/"
# weight = 1

[[main]]
name = "About"
url = "about/"
weight = 1

[[main]]
name = "Team"
url = "authors/"
weight = 2

[[main]]
name = "Research"
url = "pages/research/"
weight = 3

[[main]]
name = "Tools"
url = "tools/"
weight = 4

[[main]]
name = "Publications"
url = "publications/"
weight = 5

[[main]]
name = "Midia Coverage"
url = "midia/"
weight = 6

# [[main]]
# name = "Contact"
# url = "contact/"
# weight = 5

[[main]]
weight = 7
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Blog"
url = "blog/"

[[main]]
parent = "Pages"
name = "Categories"
url = "categories/"

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
